export default function Head() {
    return (
      <>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          precedence="default"
        />
        <link
 rel="stylesheet"
 href="https://cdnjs.cloudflare.com/ajax/libs/fontawesome/6.2.1/css/all.min.css"
 precedence="default"
 />
      </>
    )
  }
  